---
title: "Lonely Together Wrangling 1"
author: "Peter Yibo Pan"
date: "2026-03-10"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(glue)
library(knitr)
theme_set(theme_minimal())
knitr::opts_chunk$set(echo = TRUE)
```

Step 1: Import data & initial analysis
```{r data}
LTdata1 <- read_csv("Lonely Together data 1.csv")
demographics <- read_csv("Demographics.csv")
glimpse(LTdata1)

## need to select only relevant columns
LTdata2 <- LTdata1 %>% select(contains("q00")) %>%
  glimpse()
test <- is.na(LTdata2$q0001)
Ineligible 
LTdata3 <- LTdata2 %>% select( -"q0001", -"q0002", -"q0003", -"q0004")
## need to get list of column names & import into vector
q_colnames <- c("age", "gender", "gender_other") ## needs to be full length
varnames <- c(colnames(LTdata3)[1:3])
renaming <- data_frame("variables" = varnames, 
                       "names" = q_colnames )
LTdata4 <- LTdata3 %>% rename_at(
  vars(renaming$variables), ~ renaming$names)
## use vector to rename columns
```


```{r cleaning, echo=FALSE}

## separate into multiple datasets
## questions 1-4 is eligibility screening & consent

## questions 5-12 is demographics (29 total columns)
demographics <- LTdata4 %>% select(1:29)

## questions 7 gender identity and 12 racial identity needs to be condensed into single value

## questions 13, 14, and 15 are RHI (37 total columns)
RHI <- LTdata4 %>% select(30:66)
## questions 16 is DJGLS (11 total columns)
DJG <- LTdata4 %>% select(67:77)
demographics <- demographics %>% rename(ID = "Respondent ID")
no_demo <- LTdata1 %>% select(2, 44:91) %>% rename(ID= "RespondentID")

stiched_data <- demographics %>% left_join(no_demo, by = "ID")
#renaming 

library(stringr)
colnames(stiched_data) = gsub("q0013", "Peer", colnames(stiched_data))
colnames(stiched_data) = gsub("q0014", "Mentor", colnames(stiched_data))
colnames(stiched_data) = gsub("q0015", "Community", colnames(stiched_data))
colnames(stiched_data) = gsub("q0016", "Loneliness", colnames(stiched_data))
LTData5 <- stiched_data
write_csv(x = LTData5, "LTData5.csv")
## detect for incomplete surveys & missing values & extreme values (age)

LTdata6 <- read_csv("LTData6.csv")
```


```{r RHI scores}
## reverse code questions Peer 8, Community 4, 7, 9, 10 


## peer, mentor, and community subscale scores 
#     RHI_Peer = mean(ALL COLUMNS WITH PEER) 
Peer <- LTdata6 %>% select( , contains("Peer")) %>% 
  mutate(PeerMean = rowMeans(across(where(is.numeric)))) %>% glimpse()
#     RHI_Peer = mean(ALL COLUMNS WITH MENTOR) 
Mentor <- LTdata6 %>% select( , contains("Mentor")) %>% 
  mutate(MentorMean = rowMeans(across(where(is.numeric)))) %>% glimpse()
#     RHI_Peer = mean(ALL COLUMNS WITH COMMUNITY) \
Community <- LTdata6 %>% select( , contains("Community")) %>% 
  mutate(CommunityMean = rowMeans(across(where(is.numeric)))) %>% glimpse()
#     RHI_Sum = Sum(ALL RHI) 
RHI <- LTdata6 %>% select ( ,starts_with("ID")| contains("Peer") | contains("Mentor") |contains("Community") ) %>% 
  mutate(RHISum = rowSums(across(where(is.numeric) & !ID))) %>% 
  mutate(RHIMean = rowMeans(across(where(is.numeric) & !ID))) %>% glimpse()
RHI<- RHI %>%  
  mutate(PeerMean = rowMeans(across(contains("Peer")))) %>% 
  mutate(MentorMean = rowMeans(across(contains("Mentor")))) %>%
  mutate(CommunityMean = rowMeans(across(contains("Community")))) %>% glimpse()

## engagement, zest, and authenticity subscale scores


```
RHI Engagement, Authenticity, and Zest: 
Empowerment/Zest subscales
RHI-P items: 2, 7, 9, 10
RHI-M items: 5, 7, 8, 10
RHI-C items: 2, 6, 11, 12, 13
Engagement subscales
RHI-P items: 3, 4, 5, 12
RHI-M items: 3, 6, 9
RHI-C items: 1, 3, 5, 8, 14
Authenticity subscales
RHI-P items: 1, 6, 8, 11
RHI-M items: 1, 2, 4, 11
RHI-C items: 4, 7, 9, 10 
```{r EZA Subscale Scores}


RHI<- RHI %>% 
  mutate(Zest = rowMeans(across(one_of("Peer_0002", "Peer_0007", "Peer_0009", "Peer_0010", 
                                                        "Mentor_0005", "Mentor_0007", "Mentor_0008", "Mentor_0010", 
                                                        "Community_0002",   "Community_0006",  "Community_0011",  "Community_0012",  
                                                   "Community_0013") ) )) %>%
  mutate(Engagement = rowMeans(across(one_of("Peer_0003", "Peer_0004", "Peer_0005", "Peer_0012", 
                                                        "Mentor_0003", "Mentor_0006", "Mentor_0009", 
                                                        "Community_0001",   "Community_0003",  "Community_0005",  "Community_0008",  
                                                   "Community_0014") ) )) %>%
  mutate(Authenticity = rowMeans(across(one_of("Peer_0001", "Peer_0006", "Peer_0008", "Peer_0011", 
                                                        "Mentor_0001", "Mentor_0002", "Mentor_0004", "Mentor_0011", 
                                                        "Community_0004",   "Community_0007",  "Community_0009",  "Community_0010") ) )) 


```


```{r DJGLS scores}
## select for positive-coding questions
## change responses 3-5 to 1 and 1-2 to 0
reverse_code <- function(x, na.rm = FALSE) (6 - x)
LTdata7 <- LTdata6 %>% select( , starts_with("ID") | contains("Loneliness")) %>%
  select( , ends_with("0001") | ends_with("0004") | ends_with("0007") | ends_with("0008") | ends_with("0011")) %>% 
  transmute_all(reverse_code)  

Loneliness <- tribble(
  ~from, ~to,
  1, 0,
  2, 0,
  3, 1,
  4, 1,
  5, 1
)

SocialScore <- LTdata7 %>% transmute_all( ~ recode_values (.x , from = Loneliness$from, to = Loneliness$to))%>% mutate(SocialScore = rowSums(across(where(is.numeric)))) %>% glimpse()
LTdata9 <- LTdata6 %>% select( , contains("Loneliness")) %>%
  select( , -(ends_with("0001") | ends_with("0004") | ends_with("0007") | ends_with("0008") | ends_with("0011"))) %>% 
  transmute_all( ~ recode_values (.x , from = Loneliness$from, to = Loneliness$to))
EmotionalScore <- LTdata9 %>% mutate(EmotionalScore = rowSums(across(where(is.numeric)))) %>% glimpse()
DJGLS <- bind_cols(SocialScore, EmotionalScore)
DJGLS <- DJGLS %>% 
    mutate(Loneliness = rowSums(across(contains("Score"))))

```

```{r generate total sheet}
LTdata10 <- bind_cols(RHI, DJGLS) %>% select(!starts_with("ID"))
LTdata11 <- LTdata10 %>% select(!contains("00"))

write_csv(x = LTdata10, "LTData10.csv")
write_csv(x = LTdata11, "LTData11.csv")

```

```{r creating sheets with na and sheets with only complete results}
# LTdata 12 and 13 are only complete cases, data + scores vs. only scores
LTdata12 <- LTdata10[complete.cases(LTdata10),]
LTdata13 <- LTdata12 %>% select(!contains("00"))

# LTdata 14 and 15 are only incomplete cases, data + scores vs. only scores
LTdata14 <- LTdata10[rowSums(is.na(LTdata10[ ,])) != 0, ]
LTdata15 <- LTdata14 %>% select(!contains("00"))
write_csv(x = LTdata12, "LTData12.csv")
write_csv(x = LTdata13, "LTData13.csv")
write_csv(x = LTdata14, "LTData14.csv")
write_csv(x = LTdata15, "LTData15.csv")

```